name: pr-checker

on: [pull_request]

jobs:
  build:
    name: pr-checker
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golang-lint
      uses: reviewdog/action-golangci-lint@v1
      with:
        github_token: ${{ secrets.github_token }}

    - name: unit test
      run: go test ./... -v
